// <auto-generated />
using System;
using BaWebtool2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaWebtool2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250418151823_AddedRequiredErrorMessages")]
    partial class AddedRequiredErrorMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("AlgorithmDataPoint", b =>
                {
                    b.Property<Guid>("AlgorithmsAlgorithmId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DataPointsDataPointId")
                        .HasColumnType("TEXT");

                    b.HasKey("AlgorithmsAlgorithmId", "DataPointsDataPointId");

                    b.HasIndex("DataPointsDataPointId");

                    b.ToTable("AlgorithmDataPoint");
                });

            modelBuilder.Entity("BaWebtool2.Data.Algorithm", b =>
                {
                    b.Property<Guid>("AlgorithmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlgorithmDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlgorithmName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlgorithmId");

                    b.ToTable("Algorithms");
                });

            modelBuilder.Entity("BaWebtool2.Data.DataPoint", b =>
                {
                    b.Property<Guid>("DataPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AtomicAttribute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataPointDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("DataPointName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("PatientType")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ValueSet")
                        .HasColumnType("TEXT");

                    b.HasKey("DataPointId");

                    b.ToTable("DataPoints");
                });

            modelBuilder.Entity("AlgorithmDataPoint", b =>
                {
                    b.HasOne("BaWebtool2.Data.Algorithm", null)
                        .WithMany()
                        .HasForeignKey("AlgorithmsAlgorithmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaWebtool2.Data.DataPoint", null)
                        .WithMany()
                        .HasForeignKey("DataPointsDataPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
